adding statusmonitor/main.go
Juniper/contrail-operator pull request #321
Opened 2020-08-18 22:58 UTC by vijayrap

Raising a review request.

2020-08-19 08:46 UTC, psykulsk requested changes
Thanks @vijayrap, that's good, but more changes are required:

This function has to return error
https://github.com/Juniper/contrail-operator/blob/new_2008R_update_CEM-18251/statusmonitor/config_status_monitor.go#L56
Instead of doing log.Fatalf() here https://github.com/Juniper/contrail-operator/blob/new_2008R_update_CEM-18251/statusmonitor/config_status_monitor.go#L89

Same with the getControlStatus, it should return error:
https://github.com/Juniper/contrail-operator/blob/new_2008R_update_CEM-18251/statusmonitor/main.go#L118
instead of log.Fatalf: https://github.com/Juniper/contrail-operator/blob/new_2008R_update_CEM-18251/statusmonitor/main.go#L136
and here https://github.com/Juniper/contrail-operator/blob/new_2008R_update_CEM-18251/statusmonitor/main.go#L123

Then, in the main for loop, you can check those errors and log them here https://github.com/Juniper/contrail-operator/blob/new_2008R_update_CEM-18251/statusmonitor/main.go#L107 and here https://github.com/Juniper/contrail-operator/blob/new_2008R_update_CEM-18251/statusmonitor/main.go#L109 .
Thanks to that, they will be logged but the process will not exit.

2020-08-20 08:38 UTC, Dysproz approved these changes
LGTM. One NIT comment

2020-08-20 08:38 UTC, Dysproz commented on statusmonitor/main.go
> +					if err != nil{
It may be done as one liner:
```
if err := getControlStatus(client, clientset, restClient, config); err != nil {
```

2020-08-20 09:38 UTC, psykulsk approved these changes

2020-08-20 09:38 UTC, psykulsk commented
recheck

2020-08-20 17:11 UTC, merged