Schedule pods only on selected pods
Juniper/contrail-operator pull request #331
Opened 2020-08-25 07:26 UTC by mfigurski

2020-08-25 11:38 UTC, katrybacka requested changes

2020-08-25 11:38 UTC, katrybacka commented on pkg/controller/keystone/keystone_controller.go
> +func newBootStrapJob(cr *contrail.Keystone, name types.NamespacedName, kcbName, fernetKeysSecretName, credentialKeysSecretName string, psqlIP string, nodeSelector map[string]string) *batch.Job {
please remove `nodeSelector` argument since you can take it from `cr.CommonConfiguration.NodeSelector`

2020-08-25 11:38 UTC, katrybacka commented on test/env/deploy/cluster.yaml
> +        commonConfiguration:
why hostNetwork is needed? Move `commonConfiguration` before `serviceConfiguration` like in other components and remove hostNetwork from here it should be set at Manager level

2020-08-25 12:29 UTC, katrybacka approved these changes

2020-08-26 08:42 UTC, kaweue approved these changes

2020-08-26 08:43 UTC, merged