Vrouter static configuration
Juniper/contrail-operator pull request #397
Opened 2020-09-24 10:47 UTC by psykulsk

2020-09-25 12:19 UTC, psykulsk commented
recheck

2020-09-25 15:06 UTC, psykulsk commented
recheck

2020-09-28 05:55 UTC, Dysproz commented
recheck

2020-09-28 11:37 UTC, psykulsk commented
recheck ha

2020-09-28 13:04 UTC, Dysproz requested changes

2020-09-28 14:36 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/tests/config_vrouter_test.go
> +servers=1.1.1.1:5269 2.2.2.2:5269 3.3.3.3:5269
Yep, good idea. I will do that.

2020-09-28 15:01 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/tests/config_vrouter_test.go
> +		})
But there are cases for a fully dynamic config, a fully static config and from mixed configs, aren' there?

2020-09-28 15:04 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/tests/config_vrouter_test.go
> +				}
I think I prefer testing this way as it tests the exposed method's output, not the implementation inside the non exposed methods.

2020-09-29 05:57 UTC, Dysproz approved these changes

2020-09-29 08:20 UTC, kaweue approved these changes

2020-09-29 08:23 UTC, merged