[CEM-19380]: Added configuration for zookeeper admin server
Juniper/contrail-operator pull request #407
Opened 2020-10-01 02:00 UTC by lrebeja

2020-10-01 12:51 UTC, psykulsk requested changes
Can you add a unit test for this ZookeeperStaticConfig that will check the default values and also a case with customized values?

2020-10-01 12:51 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/templates/zookeeper_config.go
> +admin.serverPort={{ .AdminSeverPort }}
Please fix AdminSeverPort -> AdminServerPort

2020-10-01 12:51 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/zookeeper_types.go
> +		AdminSeverPort    string
Please fix AdminSeverPort -> AdminServerPort

2020-10-01 15:30 UTC, vijayrap approved these changes
LGTM.

2020-10-02 08:09 UTC, psykulsk commented
recheck ha

2020-10-02 10:01 UTC, psykulsk approved these changes

2020-10-05 02:10 UTC, merged