WIP
Juniper/contrail-operator pull request #427
Opened 2020-10-20 07:58 UTC by Janek3d

work-in-progress

2020-10-21 10:20 UTC, psykulsk requested changes

2020-10-21 10:20 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/tests/config_test.go
>  package contrailtest
I think you can also remove the device manager config string from this file, as it is not used anymore. Line 529
https://github.com/Juniper/contrail-operator/blob/943581329a30321da02f2df98cd3489bb009c8d3/pkg/apis/contrail/v1alpha1/tests/config_test.go#L529

2020-10-21 10:20 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/tests/config_test.go
> +
IF this struct is not used anywhere it should be removed.

2020-10-21 10:35 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/tests/config_customized_test.go
I think you can also remove the strings below this line as they are not used anymore.

2020-10-21 11:40 UTC, psykulsk approved these changes

2020-10-21 12:13 UTC, Dysproz commented on pkg/apis/contrail/v1alpha1/tests/config_zookeeper_test.go
> +`
remove this since it's not used

2020-10-21 12:18 UTC, Dysproz commented on pkg/apis/contrail/v1alpha1/tests/config_kubemanager_test.go
> +	"github.com/Juniper/contrail-operator/pkg/k8s"
This should be in separate block of imports

2020-10-21 15:41 UTC, dgautam commented
/gcbrun

2020-10-22 09:12 UTC, Dysproz commented
/gcbrun

2020-10-22 09:31 UTC, Dysproz commented
/gcbrun

2020-10-22 09:42 UTC, psykulsk commented
recheck

2020-10-22 10:04 UTC, psykulsk commented
recheck

2020-10-22 12:07 UTC, Dysproz approved these changes

2020-10-22 12:30 UTC, Dysproz approved these changes

2020-10-22 12:30 UTC, Dysproz commented
/gcbrun

2020-10-26 08:06 UTC, Dysproz commented
recheck

2020-10-26 08:21 UTC, psykulsk commented
recheck

2020-10-26 08:21 UTC, psykulsk commented
recheck ha

2020-10-26 08:53 UTC, psykulsk commented
recheck

2020-10-26 09:37 UTC, Dysproz commented
/gcbrun

2020-10-26 09:37 UTC, Dysproz commented
recheck

2020-10-26 09:50 UTC, psykulsk commented
recheck ha

2020-10-26 10:33 UTC, Dysproz commented
/gcbrun

2020-10-26 13:44 UTC, merged