[WIP] Vrouter env variables with user defined values
Juniper/contrail-operator pull request #432
Opened 2020-10-23 14:19 UTC by Janek3d

Add option for user to define values of vrouter env variables.

2020-10-26 09:40 UTC, Dysproz commented
/gcbrun

2020-10-26 09:41 UTC, Dysproz requested changes

2020-10-26 09:41 UTC, Dysproz commented on pkg/apis/contrail/v1alpha1/vrouter_types.go
> +	EnvVariablesConfiguration map[string]string           `json:"envVariablesConfiguration,omitempty"`
Should be inside ServiceConfiguration

2020-10-26 11:51 UTC, psykulsk requested changes

2020-10-26 11:51 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/vrouter_types.go
> +	EnvVariablesConfiguration map[string]string `json:"envVariablesConfiguration,omitempty"`
You added it to VrouterConfiguration struct already, so you do not need to add it here again

2020-10-27 08:34 UTC, Dysproz commented
/gcbrun

2020-10-27 08:35 UTC, Dysproz commented
recheck

2020-10-27 09:49 UTC, psykulsk commented
recheck

2020-10-27 09:49 UTC, psykulsk commented
recheck ha

2020-10-27 10:18 UTC, psykulsk commented
/gcbrun

2020-10-27 10:23 UTC, closed without merging