Vrouter env variables with user defined values
Juniper/contrail-operator pull request #438
Opened 2020-10-27 10:24 UTC by Janek3d

Add possibilty for user to define value of vrouter env variables

2020-10-27 10:30 UTC, Dysproz commented
/gcbrun

2020-10-27 10:30 UTC, Dysproz commented
recheck

2020-10-27 10:31 UTC, Dysproz approved these changes

2020-10-27 10:39 UTC, psykulsk commented
recheck

2020-10-27 11:35 UTC, psykulsk commented
recheck

2020-10-27 11:35 UTC, psykulsk commented
recheck ha

2020-10-28 08:47 UTC, psykulsk requested changes

2020-10-28 08:47 UTC, psykulsk commented on deploy/crds/contrail.juniper.net_managers_crd.yaml
> +                                  type: string
What is this additionaProperties field? I do not see it anywhere in the code.

2020-10-28 08:47 UTC, psykulsk commented on deploy/crds/contrail.juniper.net_vrouters_crd.yaml
> +                  additionalProperties:
What is this additionaProperties field? I do not see it anywhere in the code.

2020-10-28 08:47 UTC, psykulsk commented on pkg/apis/contrail/v1alpha1/tests/config_vrouter_test.go
> +		}
I do not think this is required, because only after these lines you are adding the custom env variables and run InstanceConfiguration once again.

2020-10-28 08:47 UTC, psykulsk commented on deploy/crds/contrail.juniper.net_managers_crd.yaml
> +                                  type: string
Is this how map[string]string is represented in the crd?

2020-10-29 08:51 UTC, psykulsk commented
/gcbrun

2020-10-29 09:13 UTC, psykulsk commented
recheck

2020-10-29 09:13 UTC, psykulsk commented
recheck ha

2020-10-29 09:53 UTC, psykulsk commented
recheck

2020-11-02 17:01 UTC, psykulsk commented
/gcbrun

2020-11-02 17:01 UTC, psykulsk commented
recheck

2020-11-02 17:01 UTC, psykulsk commented
recheck ha

2020-11-04 14:41 UTC, psykulsk commented
/gcbrun

2020-11-04 14:41 UTC, psykulsk commented
recheck

2020-11-04 14:41 UTC, psykulsk commented
recheck ha

2020-11-04 14:56 UTC, psykulsk approved these changes

2020-11-04 15:22 UTC, psykulsk commented
recheck

2020-11-04 15:46 UTC, merged