Update kind to 0.9.0
Juniper/contrail-operator pull request #452
Opened 2020-11-05 10:03 UTC by kaweue

2020-11-05 12:07 UTC, kaweue commented
/gcbrun

2020-11-05 12:31 UTC, kaweue commented
recheck

2020-11-05 13:24 UTC, kaweue commented
recheck ha

2020-11-06 12:04 UTC, katrybacka approved these changes

2020-11-06 12:04 UTC, katrybacka commented on README.md
> +  * Go
maybe minimal version at least?

2020-11-06 12:04 UTC, katrybacka commented on README.md
> +  * Go
minimal supported

2020-11-06 12:04 UTC, katrybacka requested changes
i made a mistake and approved instead of request changes xD

2020-11-06 12:06 UTC, kaweue commented on README.md
> +    kind v0.9.0 go(...) darwin/amd64
ok I will fix that

2020-11-06 12:06 UTC, kaweue commented on README.md
> +  * Go
I will change that

2020-11-06 12:22 UTC, katrybacka approved these changes

2020-11-09 08:13 UTC, kabart approved these changes

2020-11-09 08:27 UTC, merged