Provide possiblity to set swift service type
Juniper/contrail-operator pull request #487
Opened 2020-12-02 15:02 UTC by michalskalski

Some openstack services search endpoints by service type and may want to
try use endpoints created for internal use of contrail operator.

2020-12-02 23:07 UTC, michalskalski commented
recheck ha

2020-12-03 13:32 UTC, michalskalski commented
recheck ha

2020-12-03 14:58 UTC, michalskalski commented
recheck ha

2020-12-04 14:09 UTC, michalskalski commented
recheck

2020-12-04 14:24 UTC, michalskalski commented
recheck ha

2020-12-07 07:17 UTC, kaweue commented on pkg/controller/command/command_controller_test.go
> +func newCommand(withSwift bool) *contrail.Command {
I would prefer a new method something like:
newCommandWithSwift or newCommandWithoutSwift

2020-12-07 08:45 UTC, katrybacka requested changes

2020-12-07 08:45 UTC, katrybacka commented on pkg/controller/command/command_controller_test.go
> +	if *swift == "" {
i don't think that pointer is necessary here, `swift` could be just a string

2020-12-07 08:45 UTC, katrybacka commented on pkg/controller/command/command_controller_test.go
> +const absentCommandWithNoSwift = `
maybe it could be named `swiftUserConfiguration` i think it's more accurate

2020-12-07 08:45 UTC, katrybacka commented on pkg/controller/command/command_controller_test.go
> +const absentInitWithNoSwift = `  - data:
and here it could be called `swiftEndpoint`

2020-12-07 10:26 UTC, kaweue approved these changes

2020-12-07 11:19 UTC, katrybacka approved these changes

2020-12-07 11:23 UTC, merged